"""add_cpf_to_users

Revision ID: 3fd660bc6f01
Revises: 3ca20b5b7cb6
Create Date: 2026-05-21 18:15:19.678412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd660bc6f01'
down_revision: Union[str, Sequence[str], None] = '3ca20b5b7cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###
